▲리스트4.1 : 스칼라의 예

In [1]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5  # 1.2x(10의 5제곱) 120000

▲리스트4.2 : 벡터를 NumPy의 1차원 배열로 나타낸다

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # 1차원 배열로 벡터를 나타낸다
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


▲리스트4.3 : 행렬을 NumPy의 2차원 배열로 나타낸다

In [6]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2×3의 행렬
print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])  # 3×2의 행렬
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


▲리스트4.4：3차원 텐서를 NumPy 배열로 나타낸다

In [4]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
                      [2, 3, 4, 5],
                      [4, 5, 6, 7]],
              
                     [[1, 2, 3, 4],
                      [3, 4, 5, 6],
                      [5, 6, 7, 8]]])  # (2, 3, 4)의 3차원 텐서
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


#### □문제
 Jupyter Notebook의 셀에 NumPy로 스칼라, 벡터, 행렬, 3차원 텐서를 나타내는 배열을 하나씩 기술해 표시해 봅시다.

#### □정답 예

▲리스트4.5 : 정답 예

In [1]:
import numpy as np

# 스칼라
a = 1.5
print(a)

print()

# 벡터
b = np.array([1, 2, 3, 4, 5])
print(b)

print()

# 행렬
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)

print()

# 3차원 텐서
d = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              
              [[8, 7, 6],
               [5, 4, 3],
               [2, 1, 0]]])
print(d)

1.5

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[8 7 6]
  [5 4 3]
  [2 1 0]]]
