In [1]:
import numpy as np

1. 시그모이드 함수 의 범위(range)는? h(0) 값은? h(1)과 h(-2)중 어느 것이 큰가?

In [11]:
def h(x):
    return 1/(1+np.exp(-x))

print(h(0))
print(h(1),h(-2))
print("h(1)이 더 큽니다.")

0.5
0.7310585786300049 0.11920292202211755
h(1)이 더 큽니다.


2. 계단 함수, 시그모이드 함수, Relu 함수의 파이썬 함수를 적으시오. 단, 넘파이 배열을 입력으로 받게하시오.

In [37]:
sample_arr = np.array([-8,-4,0,0.1,2,4])

def step_fuction(x):
    y = x > 0
    return y.astype(np.int64)

print(step_fuction(sample_arr))

def sigmoid(x):
    return 1/(1+np.exp(-x))

print(sigmoid(sample_arr))

def Relu(x):
    return np.maximum(0,x)

print(Relu(sample_arr))

[0 0 0 1 1 1]
[3.35350130e-04 1.79862100e-02 5.00000000e-01 5.24979187e-01
 8.80797078e-01 9.82013790e-01]
[0.  0.  0.  0.1 2.  4. ]


3. 신경망에서 은닉층 노드의 활성함수를 선형 함수로 사용하면 은닉층을 둔 효과가 없어짐이 이해되는가? 간단히 설명해 보시오.

신경망은 활성함수의 합성함수 꼴입니다. 

활성함수로 선형함수를 사용하게 되면 n개의 층을 쌓더라도 결국 상수*X의 꼴로 직선이 되기 때문에 층을 쌓는 의미가 없습니다.

4. 다음 두 행렬 곱을 각각 계산하시오.

In [22]:
a= np.array([[1,2,0],
    [3,4,1]])
b = np.array([[1,0],
   [2,-1],
   [1,1]])

c=np.array([[1,2]])
d= ([[1,3,5],
    [2,4,6]])

print("a,b의 곱")
print(np.dot(a,b))
print("c,d의 곱")
print(np.dot(c,d))

a,b의 곱
[[ 5 -2]
 [12 -3]]
c,d의 곱
[[ 5 11 17]]


5. 다음 신경망에서 입력이x1=2,x2=-1일 때, 행렬을 이용하여 출력 y1,y2,y3을 구하는 수식을
적고,y1,y2을 구하는 파이썬 코드를 작성하시오. 단, 활성함수는 적용하지 않는다.

$y_1 = -1*2 + 2*-1 = -4$

$y_2 = 3*2 + 4*-1 = 2$

$y_3 = 5*2 + -1*-1 = 9$

In [38]:
W = np.array([[-1,3,5],
                   [2,4,-1]])
X = np.array([[2,-1]])

print(W.shape)
print(X.shape)
print(np.dot(X,W))

(2, 3)
(1, 2)
[[-4  2 11]]


6. 다음 신경망에서, 다음 주어진 값과 행렬을 이용하여 출력y1,y2을 구하는 수식을 적고, y1,y2을 구하는 파이썬 코드를 작성하시오. 단, 활성함수는 적용하지 않는다. 

$y_1 = w_{11}^{(1)}x_1 + w_{12}^{(1)}x_2+ w_{13}^{(1)}x_3 = 1*x_1 + 0*x_2 + $

$y_2 = w_{21}^{(1)}x_1 + w_{22}^{(1)}x_2+ w_{23}^{(1)}x_3$

In [35]:
W = np.array([[1,0],
              [0,2],
              [3,1]])
X = np.array([[2,1,-1]])



print(W.shape)
print(X.shape)
print(np.dot(X,W))

(3, 2)
(1, 3)
[[-1  1]]


7. 기호 $w_{32}^{(1)}$는 무엇을 의미하는가? 설명하시오. 

첫번째 층의 뉴런을 의미하며 다음층의 3번째 뉴런, 앞층의 2번째 뉴런을 의미합니다.

8. [식 3.8]과 같이 $a_2^{(1)},a_3^{(1)}$을 표현하시오. 이를 시그마 기호 $\sum$를 사용하여 나타낼 수 있는가?


$a_2^{(1)} = w_{21}^{(1)}x_1+w_{22}^{(1)}x_2 +b_2^{(1)}$


$a_3^{(1)} = w_{31}^{(1)}x_1+w_{32}^{(1)}x_2 +b_3^{(1)}$

$\sum_{i=1}^N w_{i1}^{(1)}x_1+w_{i2}^{(1)}x_2 +b_i^{(1)}$