In [47]:
# 예제 1
import numpy as np

scores = [88, 92, 75, 100, 89, 95, 73, 68, 85, 90, 78, 82, 96, 87, 91]
print("1. Numpy 배열 생성")
scores = np.array(scores)
print(scores)
print("2. Numpy 메소드를 이용해서 값을 구하시오.")
print("mean:", np.mean(scores), ", min:", np.min(scores), ", max:", np.max(scores), ", median:", np.median(scores))
print("3. 다음의 조건을 구하시오.")
print("Over 80: ", scores[scores > 80])
print("Under 70 Count:  ", len(scores[scores < 70]))
print("Sort:    ", np.sort(scores))
print("Plus 5:  ", scores + 5)

1. Numpy 배열 생성
[ 88  92  75 100  89  95  73  68  85  90  78  82  96  87  91]
2. Numpy 메소드를 이용해서 값을 구하시오.
mean: 85.93333333333334 , min: 68 , max: 100 , median: 88.0
3. 다음의 조건을 구하시오.
Over 80:  [ 88  92 100  89  95  85  90  82  96  87  91]
Under 70 Count:   1
Sort:     [ 68  73  75  78  82  85  87  88  89  90  91  92  95  96 100]
Plus 5:   [ 93  97  80 105  94 100  78  73  90  95  83  87 101  92  96]


In [31]:
#예제 2
import numpy as np
class_A = [78, 85, 90, 88, 76, 95, 89, 84, 91, 87, 80, 93, 72, 99, 83, 77, 94, 86, 81, 79]
class_B = [82, 79, 88, 92, 75, 89, 90, 80, 86, 85, 78, 96, 74, 100, 82, 76, 97, 84, 83, 81]

class_A = np.array(class_A)
class_B = np.array(class_B)
print("두 반의 평균 점수를 비교하고, 어느 반의 평균이 더 높은지 출력하시오")
print("Class A 평균 점수:", np.mean(class_A),"Class B 평균 점수:", np.mean(class_B))
print("Class A"if np.mean(class_A) > np.mean(class_B) else "Class B")
print("두 반의 중앙값과 표준 편차(Standard Deviation)를 구하시오")
print("Class A 중앙값:", np.median(class_A), ", 표준 편차:", np.std(class_A))
print("두 반의 최상위 5명의 점수를 비교하여, 어느 반이 더 높은 점수를 가졌는지 분석하시오.")
print("Class A Top 5:", np.sort(class_A)[-5:], ", Class B Top 5:", np.sort(class_B)[-5:])
print("Class A" if np.mean(np.sort(class_A)[-5:]) > np.mean(np.sort(class_B)[-5:]) else "Class B")
print("반별 80점 이상인 학생의 비율을 계산하고, 더 높은 비율을 가진 반을 출력하시오.")
print("Class A 80점 이상 비율:", len(class_A[class_A >= 80]) / len(class_A) * 100, "%")
print("Class B 80점 이상 비율:", len(class_B[class_B >= 80]) / len(class_B) * 100, "%")
print("Class A" if len(class_A[class_A >= 80]) / len(class_A) > len(class_B[class_B >= 80]) / len(class_B) else "Class B")

두 반의 평균 점수를 비교하고, 어느 반의 평균이 더 높은지 출력하시오
Class A 평균 점수: 85.35 Class B 평균 점수: 84.85
Class A
두 반의 중앙값과 표준 편차(Standard Deviation)를 구하시오
Class A 중앙값: 85.5 , 표준 편차: 6.980508577460527
두 반의 최상위 5명의 점수를 비교하여, 어느 반이 더 높은 점수를 가졌는지 분석하시오.
Class A Top 5: [91 93 94 95 99] , Class B Top 5: [ 90  92  96  97 100]
Class B
반별 80점 이상인 학생의 비율을 계산하고, 더 높은 비율을 가진 반을 출력하시오.
Class A 80점 이상 비율: 75.0 %
Class B 80점 이상 비율: 75.0 %
Class B


In [45]:
#예제 3
import numpy as np
# 4개 도시(서울, 부산, 대구, 광주)의 1주일 기온 데이터
city_temps = [
[12.3, 14.1, 15.8, 13.5, 16.2, 17.0, 14.8], # 서울
 [15.2, 16.8, 18.1, 17.4, 19.0, 20.5, 18.6], # 부산
 [14.5, 15.9, 17.3, 16.0, 18.2, 19.8, 17.5], # 대구
 [13.8, 15.2, 16.5, 14.9, 17.0, 18.3, 16.1] # 광주
]
city_temps = np.array(city_temps)
print("1. 4개 도시의 7일간 평균 기온")
print("서울:", np.mean(city_temps[0]), "부산:", np.mean(city_temps[1]), "대구:", np.mean(city_temps[2]), "광주:", np.mean(city_temps[3]))
print("2. 각 도시별 최저 및 최고 기온")
print("서울: 최저", np.min(city_temps[0]), "최고", np.max(city_temps[0]), 
    "부산: 최저", np.min(city_temps[1]), "최고", np.max(city_temps[1]), 
    "대구: 최저", np.min(city_temps[2]), "최고", np.max(city_temps[2]), 
    "광주: 최저", np.min(city_temps[3]), "최고", np.max(city_temps[3]))
print("3. 일주일 동안 전국 평균 기온")
print(np.mean(city_temps, axis=0))
print("4. 평균 기온이 16도 이상인 날과, 해당 날짜의 모든 도시 기온")
print("서울:", city_temps[0][city_temps[0] >= 16])
print("부산:", city_temps[1][city_temps[1] >= 16])
print("대구:", city_temps[2][city_temps[2] >= 16])
print("광주:", city_temps[3][city_temps[3] >= 16])
print("5.모든 기온을 화씨로 변환")
print(city_temps * 9/5 + 32)
print("6. 가장 기온 변화가 심한 도시")
print("서울:", np.max(city_temps[0]) - np.min(city_temps[0]))
print("부산:", np.max(city_temps[1]) - np.min(city_temps[1]))
print("대구:", np.max(city_temps[2]) - np.min(city_temps[2]))
print("광주:", np.max(city_temps[3]) - np.min(city_temps[3]))


1. 4개 도시의 7일간 평균 기온
서울: 14.814285714285715 부산: 17.942857142857143 대구: 17.02857142857143 광주: 15.971428571428573
2. 각 도시별 최저 및 최고 기온
서울: 최저 12.3 최고 17.0 부산: 최저 15.2 최고 20.5 대구: 최저 14.5 최고 19.8 광주: 최저 13.8 최고 18.3
3. 일주일 동안 전국 평균 기온
[13.95  15.5   16.925 15.45  17.6   18.9   16.75 ]
4. 평균 기온이 16도 이상인 날과, 해당 날짜의 모든 도시 기온
서울: [16.2 17. ]
부산: [16.8 18.1 17.4 19.  20.5 18.6]
대구: [17.3 16.  18.2 19.8 17.5]
광주: [16.5 17.  18.3 16.1]
5.모든 기온을 화씨로 변환
[[54.14 57.38 60.44 56.3  61.16 62.6  58.64]
 [59.36 62.24 64.58 63.32 66.2  68.9  65.48]
 [58.1  60.62 63.14 60.8  64.76 67.64 63.5 ]
 [56.84 59.36 61.7  58.82 62.6  64.94 60.98]]
6. 가장 기온 변화가 심한 도시
서울: 4.699999999999999
부산: 5.300000000000001
대구: 5.300000000000001
광주: 4.5


In [46]:
#예제 4
import numpy as np

cost_price = [12000, 8500, 15000, 9900, 21000, 30000, 17500, 19900, 12500, 28000]
sell_price = [15000, 10000, 18000, 12000, 25000, 35000, 21000, 23000, 15500, 31000]
cost_price = np.array(cost_price)
sell_price = np.array(sell_price)

print("1. 각 제품의 이익(판매가 - 원가)을 구하고, 가장 높은 이익을 내는 제품을 찾으시오.(제품의 색인값과 이익 출력)")
profit = sell_price - cost_price
print("이익:", profit)
print("가장 높은 이익을 내는 제품:", np.argmax(profit), "이익:", np.max(profit))
print("2. 평균 이익률(이익 / 원가 * 100)을 구하시오.")
profit_rate = (profit / cost_price) * 100
print("평균 이익률:", np.mean(profit_rate), "%")
print("3. 원가가 15,000원 이하인 제품 중 이익이 3,000원 이상인 제품을 찾으시오.(제품의 색인값 출력)")
mask = (cost_price <= 15000) & (profit >= 3000)
print(np.where(mask)[0])
print("4. 20,000원 이상인 제품의 판매가를 15% 할인했을 때, 할인 후 가격이 18,000원 이상인 제품만출력하시오. (제품의 색인값 출력)")
mask = (sell_price >= 20000) & ((sell_price * 0.85) >= 18000)
print(np.where(mask)[0])

1. 각 제품의 이익(판매가 - 원가)을 구하고, 가장 높은 이익을 내는 제품을 찾으시오.(제품의 색인값과 이익 출력)
이익: [3000 1500 3000 2100 4000 5000 3500 3100 3000 3000]
가장 높은 이익을 내는 제품: 5 이익: 5000
2. 평균 이익률(이익 / 원가 * 100)을 구하시오.
평균 이익률: 18.986564091145823 %
3. 원가가 15,000원 이하인 제품 중 이익이 3,000원 이상인 제품을 찾으시오.(제품의 색인값 출력)
[0 2 8]
4. 20,000원 이상인 제품의 판매가를 15% 할인했을 때, 할인 후 가격이 18,000원 이상인 제품만출력하시오. (제품의 색인값 출력)
[4 5 7 9]
