In [1]:
import numpy as np

In [2]:
W=np.arange(21).reshape(7,3)

In [3]:
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [4]:
W[2]

array([6, 7, 8])

In [5]:
W[5]

array([15, 16, 17])

In [6]:
idx=np.array([1,0,3,0]) #원하는 팽 번호들을 배열에 명시, 인덱스 4개(1,0,3,0)번째 행을 한꺼번에 추출
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [7]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)] 
        self.idx = None

    def forward(self, idx): 
        W, = self.params
        self.idx = idx
        out = W[idx] #슬라이싱
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout) #중복문제 해결을 위해 dh각 행의 값을 dW의 해당행에 더해준다.
        return None



In [8]:
import numpy as np

In [9]:
dW=np.zeros((3,3))

In [10]:
dout=np.arange(12).reshape(4,3)


In [11]:
idx=[0,2,1,2]

In [12]:
dW

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
dout

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
idx

[0, 2, 1, 2]

In [15]:
np.add.at(dW,idx,dout)

In [16]:
dW

array([[ 0.,  1.,  2.],
       [ 6.,  7.,  8.],
       [12., 14., 16.]])

In [17]:
class EmbeddingDot:
    def __init__(self, W): 
        self.embed = Embedding(W)
        self.params = self.embed.params
        self.grads = self.embed.grads
        self.cache = None

    def forward(self, h, idx):
        target_W = self.embed.forward(idx)
        out = np.sum(target_W * h, axis=1)

        self.cache = (h, target_W)
        return out

    def backward(self, dout):
        h, target_W = self.cache
        dout = dout.reshape(dout.shape[0], 1)

        dtarget_W = dout * h
        self.embed.backward(dtarget_W)
        dh = dout * target_W
        return dh

In [18]:

W_out = np.arange(1,13).reshape(3,4)
h = np.array([[0,-1,1],[-1,0,1],[-1,-1,1]])
ds = np.array([1,2,3])
t = np.array([2,0,0])

ED = EmbeddingDot(W_out.T)

print(ED.forward(h,t))
print(ED.backward(ds))
print(ED.grads[0])

[4 8 3]
[[ 3  7 11]
 [ 2 10 18]
 [ 3 15 27]]
[[-5 -3  5]
 [ 0  0  0]
 [ 0 -1  1]
 [ 0  0  0]]


In [19]:
import sys
sys.path.append('common') # 각자의 경로로 수정해주세요.
import numpy as np
from common.layers import Embedding

W_in = np.arange(1,13).reshape(4,3)
idx = np.array([2,0,3,0])
dh = np.array([[0,1,1],[1,0,1],[1,1,0],[1,1,1]])

Emb = Embedding(W_in)
print(Emb.forward(idx))

Emb.backward(dh)
print(Emb.grads[0])

[[ 7  8  9]
 [ 1  2  3]
 [10 11 12]
 [ 1  2  3]]
[[2 1 2]
 [0 0 0]
 [0 1 1]
 [1 1 0]]


In [20]:
W_out = np.arange(1,13).reshape(3,4)
h = np.array([[0,-1,1],[-1,0,1],[-1,-1,1]])
ds = np.array([1,2,3])
t = np.array([2,0,0])

ED = EmbeddingDot(W_out.T)

print(1)
print(2)
print(3)

1
2
3
