In [69]:
import numpy as np
import pandas as pd

배열을 입력하고 음영으로 된 부분을 출력

In [38]:
a1 = np.array([[1,7,3,10],
                [4,5,8,11],
                [3,6,9,12]])

print(a1[1:3,1:3])


[[5 8]
 [6 9]]


In [40]:
print(a1[a1>2])
a1.sort(axis=1)
print(a1)

[ 3  7 10  4  5  8 11  3  6  9 12]
[[ 1  3  7 10]
 [ 4  5  8 11]
 [ 3  6  9 12]]


In [48]:
ttrain = pd.read_csv("titanic_train.csv")

type(ttrain)

ttrain.value_counts("Survived")


Survived
0    549
1    342
dtype: int64

In [58]:
len(ttrain[ttrain['Embarked']=='Q'])

77

In [61]:
pclass_list = ttrain['Pclass'].tolist
print(pclass_list)

<bound method IndexOpsMixin.tolist of 0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64>


In [69]:
ttrain = ttrain.drop('Fare',axis=1)


KeyError: "['Fare'] not found in axis"

In [71]:
print(ttrain)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [79]:
tdrop = ttrain.drop(labels=range(101,len(ttrain)),axis=0)

In [80]:
tdrop

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
96            97         0       1   
97            98         1       1   
98            99         1       2   
99           100         0       2   
100          101         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
96                           Goldschmidt, Mr. George B    male  71.0      0   
97                     Greenfield, Mr. William Bertram    male  23.0      0   
98                Doling, Mrs. John T (Ada Julia Bone)  female  34.0      0   
99                                   Kantor, Mr. Sinai    male  34.0      1   
100                            Petranec, Miss. Matilda  female  28.0      0   

     Parch            Ticket    Cabin Embarked  
0        0         A/5 21171      NaN        S  
1        0          PC 17599      C85        C  
2        0  STON/O2. 3101282      NaN        S  
3        0            113803     C123        S  
4        0            373450      NaN        S  
..     ...               ...      ...      ...  
96       0          PC 17754       A5        C  
97       1          PC 17759  D10 D12        C  
98       1            231919      NaN        S  
99       0            244367      NaN        S  
100      0            349245      NaN        S  

[101 rows x 11 columns]

In [1]:
A = np.array([[1,0],[0,-1]])
B = np.array([[1,2,1],[2,0,1]])
At = A.transpose()
At.dot(B)

NameError: name 'np' is not defined

In [24]:
score = [ 87, 94, 97, 86, 97, 79, 98, 86, 91, 94, 91, 96, 87, 96, 82, 89, 97, 88, 78, 88, 94, 83, 94, 81, 94, 89, 92, 84, 99, 93, 88, 97, 89]
score = np.array(score)
score_arg = np.argsort(score)[::-1]
score = np.sort(score)[::-1]

print(score_arg[0],"번:",score[0]," ",score_arg[1],"번:",score[1]," ",score_arg[2],"번:",score[2],)

28 번: 99   6 번: 98   16 번: 97


In [70]:
examdata = {'이름':['서준','우현','민아'],
            '국어':[12,25,12],
            '수학':[24,52,75]}


#df = pd.DataFrame(examdata,index=examdata['이름'])
df1 = pd.DataFrame(examdata)
df1.set_index('이름',inplace=True)

df1.loc['민아','수학']
df1['영어'] = [42,21,23]
df1.loc[['서준','우현']]

국어  수학  영어
이름            
서준  12  24  42
우현  25  52  21

In [71]:
df1.loc['동규'] = [12,42,63]
df1 = df1.T
df1

이름  서준  우현  민아  동규
국어  12  25  12  12
수학  24  52  75  42
영어  42  21  23  63

In [76]:
df1 = df1.T
df1

국어  수학  영어
이름            
서준  12  24  42
우현  25  52  21
민아  12  75  23
동규  12  42  63

In [91]:
add = (df1.loc['서준']).add(df1.loc['민아']).add(df1.loc['우현']).add(df1.loc['동규'])
add

국어     61.0
수학    193.0
영어    149.0
합계      NaN
dtype: float64