In [1]:
import matplotlib_inline as plt
import pandas as pd
import numpy as np

file = "./data/시도별 전출입 인구수.xlsx"



조별과제 조원의 고향 2곳 이상 선택
2000~2010 전입인구 선택 및 시각화

In [6]:
df = pd.read_excel(file)
df.fillna("전국")
#수원,구미,

전출지별     전입지별      1970      1971      1972      1973      1974  \
0    전출지별     전입지별  이동자수 (명)  이동자수 (명)  이동자수 (명)  이동자수 (명)  이동자수 (명)   
1      전국       전국   4046536   4210164   3687938   4860418   5297969   
2      전국    서울특별시   1742813   1671705   1349333   1831858   2050392   
3      전국    부산광역시    448577    389797    362202    482061    680984   
4      전국    대구광역시         -         -         -         -         -   
..    ...      ...       ...       ...       ...       ...       ...   
320    전국     전라북도       139       202       141       210       219   
321    전국     전라남도       631       965       857       952      1133   
322    전국     경상북도       374       619       468       576       625   
323    전국     경상남도       474       479       440       571      1208   
324    전국  제주특별자치도      9290     12427     12210     16158     19580   

         1975      1976      1977  ...      2008      2009      2010  \
0    이동자수 (명)  이동자수 (명)  이동자수 (명)  ...  이동자수 (명)  이동자수 (명)  이동자수 (명)   
1     9011440   6773250   7397623  ...   8808256   8487275   8226594   
2     3396662   2756510   2893403  ...   2025358   1873188   1733015   
3      805979    724664    785117  ...    514502    519310    519334   
4           -         -         -  ...    409938    398626    370817   
..        ...       ...       ...  ...       ...       ...       ...   
320       415       392       408  ...       668       579       672   
321      2808      2608      2652  ...      1143      1123      1002   
322      1123      1141      1004  ...       761       704       738   
323      1517       863      1122  ...      1517      1474      1324   
324     34221     23291     31028  ...     59564     55673     55507   

         2011      2012      2013      2014      2015      2016      2017  
0    이동자수 (명)  이동자수 (명)  이동자수 (명)  이동자수 (명)  이동자수 (명)  이동자수 (명)  이동자수 (명)  
1     8127195   7506691   7411784   7629098   7755286   7378430   7154226  
2     1721748   1555281   1520090   1573594   1589431   1515602   1472937  
3      508043    461042    478451    485710    507031    459015    439073  
4      370563    348642    351873    350213    351424    328228    321182  
..        ...       ...       ...       ...       ...       ...       ...  
320       561       551       516       609       683       733       768  
321      1026       966      1001       928      1062      1127      1102  
322       756       699       781       728       903       931       994  
323      1367      1227      1278      1223      1500      1448      1501  
324     59846     54280     60607     59673     59036     66444     63275  

[325 rows x 50 columns]

수업내용

In [17]:
ar4 = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
ar4.shape
print(ar4)
print("{}".format(ar4.ndim))

[[[1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]]]
3


In [21]:
ar5 = np.array([[[1,2,3],[2,4,2]],[[5,3,2],[3,2,3]]])
print(ar5.shape,"")
print(ar5.ndim)

(2, 2, 3) 
3


In [29]:
ar6 = np.array([[
    [[5,3,3,9],[1,2,3,3],[2,4,3,2]],
    [[5,3,3,9],[1,2,3,3],[2,4,3,2]]
                                    ]])
print(ar6.shape)

(1, 2, 3, 4)


In [33]:
ar6_uni = ar6.astype('unicode')
print(ar6_uni.dtype)

ar6_uni

<U11


array([[[['5', '3', '3', '9'],
         ['1', '2', '3', '3'],
         ['2', '4', '3', '2']],

        [['5', '3', '3', '9'],
         ['1', '2', '3', '3'],
         ['2', '4', '3', '2']]]], dtype='<U11')