In [1]:
import numpy as np
class sigmoid():
    def __init__(self):
        self.out = None

    def forward(self, x):
        self.out = 1 / (1 + np.exp(-x))
        return self.out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx
    
sigmoid = sigmoid()
x = np.array([1.0, 2.0, 3.0])
print(sigmoid.forward(x))
print(sigmoid.backward(1))

X = np.random.rand(2, 3)
W = np.random.rand(3, 2)
B = np.random.rand(2)

X = np.dot(X, W) + B
X

[0.73105858 0.88079708 0.95257413]
[0.19661193 0.10499359 0.04517666]


array([[0.96969454, 1.26502691],
       [0.80128262, 0.9019797 ]])

In [ ]:
X_dot_W = np.array([[0, 0, 0], [10, 10, 10]])
B = np.array([1, 2, 3])
X_dot_W + B

In [4]:
dY = np.array([[1, 2, 3], 
               [4, 5, 6]])
dB = np.sum(dY, axis=0)
dB

array([5, 7, 9])

In [ ]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    if t.size == y.size:
        t = t.argmax(axis=1)
             
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

class Affine():
    def __init__(self,w,b):
        self.w = w
        self.b = b
        self.x = None
        self.shape_x = None
        self.dw = None
        self.db = None
    def forward(self, x):
        self.shape_x = x.shape
        self.x = x.reshape(x.shape[0], -1)
        
        return np.dot(self.x, self.w) + self.b
    
    def backword(self, dout):
        dx = np.dot(dout, self.w.T)
        self.dw = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        dx = dx.reshape(*self.shape_x)
        return dx
    

class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None # 손실함수
        self.y = None    # softmax의 출력
        self.t = None    # 정답 레이블(원-핫 인코딩 형태)
        
    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        
        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        if self.t.size == self.y.size: # 정답 레이블이 원-핫 인코딩 형태일 때
            dx = (self.y - self.t) / batch_size
        else:
            dx = self.y.copy()
            dx[np.arange(batch_size), self.t] -= 1
            dx = dx / batch_size
        
        return dx
