다음 행렬 A 와 벡터 x,y 에 대하여 다음 질문에 답하시오. LaTex을 이용하여 Markdown셀에 답을 쓰시오. 참고:
 $$ A = \begin{pmatrix} -1&1\\ 5&3\\ \end{pmatrix} \vec{x} = \begin{pmatrix} -1,&2 \end{pmatrix} , \vec{y} = \begin{pmatrix} 1,&1 \end{pmatrix} $$
 

 (1)
  $$  \vec{x} {}\vec{y} = 1-2  따라서 직교하지 않음$$

(2)
$$ 코사인 유사도 =  {\vec{x}\cdot\vec{y} \over \sqrt{5}\sqrt{2}} =  {-1\over \sqrt{10}}$$

(3)
$$ A\vec{x} = \begin{pmatrix} -3,&-1 \end{pmatrix}$$

(4)고유값
$$det(A-\lambda E) = 0=\begin{pmatrix} -1&1\\ 5&3\\ \end{pmatrix}  - \lambda \begin{pmatrix} 1&0\\ 0&1\\ \end{pmatrix}  ,\lambda  = 4 { or}-2 $$
고유벡터
$$ \lambda = 4 , {1\over \sqrt{26}}\begin{pmatrix} 5,&1 \end{pmatrix} $$
$$ \lambda = -1 , {1\over \sqrt{2}}\begin{pmatrix} 1,&-1 \end{pmatrix} $$

고유값 을행렬로 만들면 d= ([1 , 0],
                            [0 , 5]) 고유벡터를 행렬로 만들면 p = [[1,1],
                                                                [-1,3]]
a = [[2,1],[3,4]]
ap = [[1,2],[-1,15]]
dp = [[1,1],
    [-5,15]]

In [7]:
#고유값 을행렬로 만들면 d= ([1 , 0],[0 , 5]) 고유벡터를 행렬로 만들면 p = [[1,1]=,                             [-1,3]]

import numpy as np
a = np.array([[2,1],[3,4]])
d = np.array([[1,0],[0,5]])
p = np.array([[1,1],[-1,3]])
print(a.dot(p))
print(p.dot(d))
#p^-1 
#app^-1 = pdp^-1

#a^3 = (pdp^-1)(pdp^-1)(pdp^-1) = pd^3p^-1 ,대각행렬은 [[a^n,0], [0,d^n] ]
print("d^3= \n",d.dot(d.dot(d)))



[[ 1  5]
 [-1 15]]
[[ 1  5]
 [-1 15]]
d^3= 
 [[  1   0]
 [  0 125]]


In [19]:
#(5)두  ,  는 직교함을 보이기 위해, 필요한 계산을 수행하는 프로그램을 작성하시오
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt


x = np.array([1, -2]) 
y = np.array([1,1])

A = np.array([[-1, 1],
              [5, 3]])
result = x.dot(y)
if (result ==0):
    print(result,"이므로 직교한다.")
else:
    print(result,"이므로 직교하지 않는다.")


-1 이므로 직교하지 않는다.


In [20]:
#(6) 두 벡터의 코사인 유사도를 구하는 프로그램을 작성하시오

def cos_sim(vec_1,vec_2):
    return np.dot(vec_1,vec_2)/(np.linalg.norm(vec_1)*np.linalg.norm(vec_2))



print(cos_sim(x,y))

-0.31622776601683794


In [12]:
#(7) 벡터  가 행렬  에 의해 변환(대응)되는 벡터를 구하는 프로그램을 작성하시오.

print(A.dot(x))

[-3 -1]


In [16]:
#(8) 행렬  의 고유값과 고유벡터를 구하는 프로그램을 작성하시오. 단, 마지막에 print문으로 고유벡터와 대응하는 고유벡터를 각각 보기좋게 출력하시오. 

ev = np.linalg.eig(A)

print("고유값:",ev[0])
print("고유벡터")
print(ev[1])


고유값: [-2.  4.]
고유벡터
[[-0.70710678 -0.19611614]
 [ 0.70710678 -0.98058068]]
