In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

 $$ A = \begin{pmatrix} 0&1\\ 1&2\\ \end{pmatrix} B = \begin{pmatrix} 2&1&3 \\ -1&1&0\\ \end{pmatrix}$$

 $$ A^t와 B^t 를 구하시오.$$
 
 $$ A^t = \begin{pmatrix} 0&1\\ 1&2\\ \end{pmatrix}
  B^t = \begin{pmatrix} 2&-1 \\ 1&1\\ 3&0\\ \end{pmatrix}$$
 


$$ AB = \begin{pmatrix}  -1&1&0\\ 0&3&3\\ \end{pmatrix}$$


$$A \circ A^t =  \begin{pmatrix}  0&1\\ 1&4\\ \end{pmatrix}$$


$$ A-A^t = \begin{pmatrix}  0&0\\ 0&0\\ \end{pmatrix}$$

$$|A| = det A = 0*1 - 1*2 =  -1$$

$$A^{-1} = {1\over2*1 - 1*0}\begin{pmatrix}   0&-1 \\ -1&2 \end{pmatrix} = \begin{pmatrix}   -2&1 \\ 1&0 \end{pmatrix}  $$

$$ \sum_{k=1}^l a_{1k}b_{k2} ,  \sum_{k=1}^l a_{ik}b_{kj} $$ 


In [26]:
#(8) 파이썬 프로그램을 작성하여, 위 (1) ~ (6)의 결과를 확인하시오.

a = np.array([[0, 1],
              [1, 2]]) 
at = a.T


adet = np.linalg.det(a)
arev = np.linalg.inv(a)


b = np.array([[2,1,3],
              [-1,1,0],
              ])  # 3×2의 행렬
bt = b.T

print("At와 Bt")
print(at)
print()
print(bt)
print()

print("AB")
print(a.dot(b))
print()

print("AoB")
print(np.multiply(a,at))
print()

print("A-At")
print(a-at)
print()

print("A-At")
print(a-at)
print()

print("Adet")
print(adet)
print()

print("Areverse")
print(arev)
print()

At와 Bt
[[0 1]
 [1 2]]

[[ 2 -1]
 [ 1  1]
 [ 3  0]]

AB
[[-1  1  0]
 [ 0  3  3]]

AoB
[[0 1]
 [1 4]]

A-At
[[0 0]
 [0 0]]

A-At
[[0 0]
 [0 0]]

Adet
-1.0

Areverse
[[-2.  1.]
 [ 1.  0.]]



In [35]:
#(9) 다음 행렬의 행렬식과 역행렬을 구하시오.

c = [[0,1,2],
     [2,4,3],
     [0,1,1]]
c = np.array(c)
cdet = np.linalg.det(c)
crev = np.linalg.inv(c)
print("행렬식:",cdet,"\n")
print("역행렬\n",crev)

행렬식: 2.0 

역행렬
 [[ 0.5  0.5 -2.5]
 [-1.   0.   2. ]
 [ 1.  -0.  -1. ]]


$$  
  Cx = \begin{pmatrix}  0&1&2\\ 2&4&3\\ 0&1&1\\ \end{pmatrix}\begin{pmatrix}  1\\ 2\\ 3\\ \end{pmatrix}
  $$

In [41]:
#(10) 위 행렬  와 벡터     의 곱   를 구하시오.
#<참고> 행렬(선형변환)  에 의해 벡터  는   로 변환된다(옮겨진다)고 말한다.
x = np.array([1,2,3])

print(c.dot(x.T))



[ 8 19  5]
