In [1]:
import numpy as np
import pandas as pd

In [2]:
array_int = np.array([1,4,2,5])
print(array_int)

#astype으로 형변환 가능
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_int.astype('int32')
print(array_int1,array_int1.dtype)

[1 4 2 5]
[1. 4. 2. 5.] float64
[1 4 2 5] int32


In [3]:
#array 자동 생성
s_array = np.arange(18)
print(s_array)
print(s_array.dtype)
print(s_array.shape,"\n")

#r:3 c:2의 0을 만들어준다. 
zero_ar = np.zeros((3,2),dtype='int32')
print(zero_ar)
print(zero_ar.shape)
print(zero_ar.dtype,"\n")


#1을 만들어준다. dtype의 default는 flaot
one_ar = np.ones((3,2))
print(one_ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
int32
(18,) 

[[0 0]
 [0 0]
 [0 0]]
(3, 2)
int32 

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
#reshape 차원변경가능 1차원 ar -> 2차원 ar

print(s_array)



s_array = s_array.reshape(6,3)

print(s_array)
print("행렬:",s_array.shape,"\n")

s_array = s_array.reshape(9,-3)
print(s_array)
print("행렬:",s_array.shape,"\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
행렬: (6, 3) 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
행렬: (9, 2) 



In [5]:
ar3d = np.arange(27)
#list형태로 print
print(ar3d.tolist(),"\n")


ar3d = ar3d.reshape(3,3,3)
print(ar3d,"\n")
print(ar3d.tolist())

ar2d =ar3d.reshape(-1,1)
print(ar2d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]]


In [6]:
#indexing
#arange의 값을 변경가능

indexingarr = np.arange(start=2,stop=10)
val = indexingarr[2]

print(indexingarr)
print(val)
#맨 뒷값 출력
print(indexingarr[-1])
#맨 뒤에서 하나 앞
print(indexingarr[-2])

indexingarr[-1] = 120
print(indexingarr[-1])

#slicing

s_array = s_array.reshape(6,3)
print(s_array)

#indexing 2dimention
print(s_array[1:4,2:3])

#fancy indexing
print(s_array[1,[0,1]])

#Boolean indexing
print(s_array[s_array > 9])

[2 3 4 5 6 7 8 9]
4
9
8
120
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 5]
 [ 8]
 [11]]
[3 4]
[10 11 12 13 14 15 16 17]


In [7]:
score_array = np.array([ 87, 94, 97, 86, 97, 79, 98, 86, 91, 94, 91, 96, 87, 96, 82, 89, 97, 88, 78, 88, 94, 83, 94, 81, 94, 89, 92, 84, 99, 93, 88, 97, 89])



In [8]:
array1 = np.array([[1,4,7,10],
                  [2,5,8,11],
                  [3,6,9,12]])

print(array1[1:3,1:3])

row = len(array1)
col = len(array1[0])
print("행:",row," 열:",col)
print("차원의 개수:",array1.ndim)




[[5 8]
 [6 9]]
행: 3  열: 4
차원의 개수: 2
